### ISSUE TITLE
Deliver proper payload when no info found

### ISSUE THREAD

**Issue by kremalicious** [oceanprotocol/ens-proxy#11]
Current implementation leads to this when actually used in clients and no ENS info is found for a given address:

<img width="1032" alt="Screen Shot 2022-09-22 at 14 03 18" src="https://user-images.githubusercontent.com/90316/191754274-757249f4-2320-4f26-a57e-f550b8754e87.png">

So the API should ALWAYS return the actual json data structure for each endpoint, but with e.g. `null` or anything so clients can detect that nothing is found.

**Comment by jamiehewitt15** [comment]
I think this issue is a duplicate of https://github.com/oceanprotocol/ens-proxy/issues/14 as it looks like you've sent the request to `ens-proxy.oceanprotocol.com`. 

Currently the error messages look like this:

### No results for ens name

```
https://ens-proxy-mmro5x4tf-oceanprotocol.vercel.app/api/address?name=jellymcjellxxxyfish.eth
```

```
{
    "address": null
}
```

### Response for invalid address:

```
https://ens-proxy-mmro5x4tf-oceanprotocol.vercel.app/api/profile?address=0x99840Df5Cb42faBE0Feb8811Aaa4BC99cA6Cdd84e0
```

```
{
    "error": {
        "reason": "invalid address",
        "code": "INVALID_ARGUMENT",
        "argument": "address",
        "value": "0x99840Df5Cb42faBE0Feb8811Aaa4BC99cA6Cdd84e0"
    }
}
```

**Comment by kremalicious** [comment]
indeed, nothing to do here, that was a mixup with all those CORS errors so now errors look more expectable
