### ISSUE TITLE
add ENS proxy in ocean status page

### ISSUE THREAD

**Issue by EnzoVezzaro** [oceanprotocol/ens-proxy#40]
**Is your feature request related to a problem? Please describe.**
Should we add this ENS proxy to https://status.oceanprotocol.com/ ?

This is not really a feature request, it's more a discussion @bogdanfazakas .

**Comment by jamiehewitt15** [comment]
Yeah it seems like a good idea to me. We can also add the docker proxy

**Comment by jamiehewitt15** [comment]
I've created separate issues for implementing this:

- https://github.com/oceanprotocol/status-monitoring-service/issues/50
- https://github.com/oceanprotocol/status-frontend/issues/8
